# Generated by Django 3.0.5 on 2020-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_WebApp', '0007_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calorie', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('FDC_ID', models.CharField(max_length=8)),
            ],
        ),
    ]
