# Generated by Django 3.0.5 on 2020-06-17 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NA_WebApp', '0009_profile_diseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_RestrictedLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NA_WebApp.Labels')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NA_WebApp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_RestrictedIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NA_WebApp.Ingredient')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NA_WebApp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_FoodPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NA_WebApp.Labels')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NA_WebApp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NA_WebApp.Allergies')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NA_WebApp.Profile')),
            ],
        ),
    ]
