# Generated by Django 3.0.5 on 2020-06-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_WebApp', '0013_nutrient_fdc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='FDC_ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
