# Generated by Django 3.0.5 on 2020-06-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_WebApp', '0014_portion_fdc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default='recipe_default.jpg', upload_to='profile_pics'),
        ),
    ]
